org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

group=dev.polymixin
version=1.0.1

classgraph_version=4.8.192
asm_version=9.7.1

# Forge 1.20.1
forge_mixin_version=0.8.5
fmlloader_version=1.20.1-47.4.22

# NeoForge 1.21.1
neoforge_mixin_version=0.15.2+mixin.0.8.7
fancymodloader_version=4.0.43

# Fabric 1.21.1
fabric_mixin_version=0.15.5+mixin.0.8.7
fabric_loader_version=0.16.14

junit_version=5.10.2
