description = 'PolyMixin ClasspathSource for Forge 1.20.1'

dependencies {
    bundled project(':polymixin-core')
    bundled "io.github.classgraph:classgraph:${classgraph_version}"

    compileOnly "org.spongepowered:mixin:${forge_mixin_version}"
    compileOnly "net.minecraftforge:fmlloader:${fmlloader_version}"
    compileOnly "org.ow2.asm:asm:${asm_version}"
    compileOnly "org.ow2.asm:asm-tree:${asm_version}"
    compileOnly "cpw.mods:securejarhandler:2.1.10"
    testImplementation "org.spongepowered:mixin:${forge_mixin_version}"
    testImplementation "org.ow2.asm:asm:${asm_version}"
    testImplementation "org.ow2.asm:asm-tree:${asm_version}"
    testImplementation "org.ow2.asm:asm-commons:${asm_version}"
    testImplementation "org.ow2.asm:asm-util:${asm_version}"
    testImplementation "org.ow2.asm:asm-analysis:${asm_version}"
    testImplementation 'io.github.llamalad7:mixinextras-fabric:0.4.1'
    testImplementation 'com.google.guava:guava:32.1.2-jre'
    testImplementation 'com.google.code.gson:gson:2.10.1'
    testImplementation "org.junit.jupiter:junit-jupiter:${junit_version}"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation(project(':polymixin-core'))
    testImplementation(project(':polymixin-test-fixtures'))
}

tasks.named('jar', Jar) {
    manifest {
        attributes(
            'MixinConfigs': 'polymixin.mixins.json',
            'Specification-Title': 'polymixin',
            'Specification-Version': project.version,
            'Implementation-Title': 'PolyMixin (Forge)',
            'Implementation-Version': project.version
        )
    }
}
