description = 'PolyMixin ClasspathSource for Forge 1.20.1'

dependencies {
    bundled project(':polymixin-core')
    bundled "io.github.classgraph:classgraph:${classgraph_version}"

    compileOnly "org.spongepowered:mixin:${forge_mixin_version}"
    compileOnly "net.minecraftforge:fmlloader:${fmlloader_version}"
    compileOnly "org.ow2.asm:asm:${asm_version}"
    compileOnly "org.ow2.asm:asm-tree:${asm_version}"
    compileOnly "cpw.mods:securejarhandler:2.1.10"
}

tasks.named('jar', Jar) {
    manifest {
        attributes(
            'MixinConfigs': 'polymixin.mixins.json',
            'Specification-Title': 'polymixin',
            'Specification-Version': project.version,
            'Implementation-Title': 'PolyMixin (Forge)',
            'Implementation-Version': project.version
        )
    }
}
