description = 'Shared Polymixin Test Fixtures'

dependencies {
    compileOnly(project(':polymixin-core'))
    compileOnly "org.spongepowered:mixin:${forge_mixin_version}"
    compileOnly "org.ow2.asm:asm:${asm_version}"
    compileOnly "org.ow2.asm:asm-tree:${asm_version}"
    compileOnly "org.ow2.asm:asm-commons:${asm_version}"
}